
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

stages:          # List of stages for jobs, and their order of executionj
  - build
  - test
  #- lint

variables:
  DOCKER_IMAGE_TAG: bralw-stars-stats:$CI_COMMIT_SHORT_SHA      #nom dans le registry
  DOCKER_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT/$DOCKER_IMAGE_TAG   #image docker avec lien vers registry


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_ROBOT_TOKEN $CI_REGISTRY
  - docker info
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - shell
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_ROBOT_TOKEN $CI_REGISTRY
  - docker info
  script:
    - docker run $DOCKER_IMAGE_NAME npm run test
  

#lint-test-job:   # This job also runs in the test stage.v
#  stage: test    # It can run at the same time as unit-test-job (in parallel).
#  tags:
#    - shell
#  before_script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker info
#  script:
#    - docker run $DOCKER_IMAGE_NAME npm run lint

